#!/bin/bash
#
# Initialize coinshift_app for a test user (Alice, Bob, Charles)
#
# Creates a data directory and a start script for the given user at a specific
# location. Each user gets unique RPC and P2P ports so multiple instances
# can run for testing.
#
# Usage:
#   ./init_coinshift_app.sh <base_location> <user>
#
# Arguments:
#   base_location  Directory where user subdirs will be created (e.g. ./test-users)
#   user           One of: alice, bob, charles, all (case-insensitive)
#                  "all" initializes alice, bob, and charles in one go.
#
# Examples:
#   ./init_coinshift_app.sh /home/parallels/Projects/coinshift-rs/test-users alice
#   ./init_coinshift_app.sh ./test-users bob
#   ./init_coinshift_app.sh ./test-users all    # init alice, bob, charles
#
# After init, start a user's app with:
#   <base_location>/<user>/start.sh
# Or run the printed command manually.
#

set -e

BASE_LOCATION="${1:-}"
USER_INPUT="${2:-}"

# Coinshift app binary: env COINSHIFT_APP or repo target/debug/coinshift_app
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
COINSHIFT_APP="${COINSHIFT_APP:-$REPO_ROOT/target/debug/coinshift_app}"
MAINCHAIN_GRPC_URL="${MAINCHAIN_GRPC_URL:-http://127.0.0.1:50051}"

# Ports per user (RPC, P2P net)
declare -A RPC_PORT
declare -A NET_PORT
RPC_PORT[alice]=6010
NET_PORT[alice]=4010
RPC_PORT[bob]=6020
NET_PORT[bob]=4020
RPC_PORT[charles]=6030
NET_PORT[charles]=4030

usage() {
    echo "Usage: $0 <base_location> <user>"
    echo ""
    echo "  base_location  Directory for user data (e.g. ./test-users)"
    echo "  user           alice, bob, charles, or all"
    echo ""
    echo "Examples:"
    echo "  $0 ./test-users alice"
    echo "  $0 ./test-users all    # init alice, bob, charles"
    echo ""
    echo "Start a user's app after init: <base_location>/<user>/start.sh"
}

if [ -z "$BASE_LOCATION" ] || [ -z "$USER_INPUT" ]; then
    usage
    exit 1
fi

USER="$(echo "$USER_INPUT" | tr '[:upper:]' '[:lower:]')"
if [[ "$USER" != "alice" && "$USER" != "bob" && "$USER" != "charles" && "$USER" != "all" ]]; then
    echo "ERROR: user must be alice, bob, charles, or all (got: $USER_INPUT)"
    usage
    exit 1
fi

# If "all", recurse for each user then exit
if [ "$USER" = "all" ]; then
    SCRIPT_PATH="$SCRIPT_DIR/$(basename "${BASH_SOURCE[0]}")"
    echo "Initializing coinshift_app for Alice, Bob, and Charles at $BASE_LOCATION"
    echo ""
    for u in alice bob charles; do
        "$SCRIPT_PATH" "$BASE_LOCATION" "$u"
    done
    echo "All users initialized. Start with:"
    echo "  $BASE_LOCATION/alice/start.sh"
    echo "  $BASE_LOCATION/bob/start.sh"
    echo "  $BASE_LOCATION/charles/start.sh"
    exit 0
fi

USER_RPC="${RPC_PORT[$USER]}"
USER_NET="${NET_PORT[$USER]}"
USER_DIR="$(cd "$BASE_LOCATION" 2>/dev/null && pwd)/$USER" || true
if [ -z "$USER_DIR" ]; then
    mkdir -p "$BASE_LOCATION"
    USER_DIR="$(cd "$BASE_LOCATION" && pwd)/$USER"
fi

echo "=========================================="
echo "Initialize coinshift_app for $USER"
echo "=========================================="
echo ""
echo "  Base location:  $BASE_LOCATION"
echo "  User directory: $USER_DIR"
echo "  RPC address:     127.0.0.1:$USER_RPC"
echo "  P2P (net) addr: 127.0.0.1:$USER_NET"
echo "  Mainchain gRPC: $MAINCHAIN_GRPC_URL"
echo "  Binary:         $COINSHIFT_APP"
echo ""

mkdir -p "$USER_DIR"

# Start script for this user
START_SCRIPT="$USER_DIR/start.sh"
cat > "$START_SCRIPT" << EOF
#!/bin/bash
# Start coinshift_app for $USER
# Generated by init_coinshift_app.sh

set -e
COINSHIFT_APP="\${COINSHIFT_APP:-$COINSHIFT_APP}"
MAINCHAIN_GRPC_URL="\${MAINCHAIN_GRPC_URL:-$MAINCHAIN_GRPC_URL}"
USER_DIR="\$(cd "\$(dirname "\${BASH_SOURCE[0]}")" && pwd)"

if [ ! -x "\$COINSHIFT_APP" ]; then
    echo "Binary not found or not executable: \$COINSHIFT_APP"
    echo "Build with: cargo build --bin coinshift_app"
    echo "Or set COINSHIFT_APP to your coinshift_app binary."
    exit 1
fi

echo "Starting coinshift_app for $USER (datadir=\$USER_DIR, RPC=127.0.0.1:$USER_RPC)"
exec "\$COINSHIFT_APP" \\
  --datadir "\$USER_DIR" \\
  --headless \\
  --mainchain-grpc-url "\$MAINCHAIN_GRPC_URL" \\
  --rpc-addr "127.0.0.1:$USER_RPC" \\
  --net-addr "127.0.0.1:$USER_NET" \\
  "\$@"
EOF
chmod +x "$START_SCRIPT"

# Optional: write a small env file for reference
ENV_FILE="$USER_DIR/env"
cat > "$ENV_FILE" << EOF
# coinshift_app env for $USER (reference only)
COINSHIFT_APP=$COINSHIFT_APP
MAINCHAIN_GRPC_URL=$MAINCHAIN_GRPC_URL
COINSHIFT_DATADIR=$USER_DIR
COINSHIFT_RPC_ADDR=127.0.0.1:$USER_RPC
COINSHIFT_NET_ADDR=127.0.0.1:$USER_NET
EOF

echo "Initialized."
echo ""
echo "Start $USER's app with:"
echo "  $START_SCRIPT"
echo ""
echo "Or in background:"
echo "  nohup $START_SCRIPT > $USER_DIR/coinshift.log 2>&1 &"
echo ""
echo "CLI for this user (from repo root):"
echo "  cargo run --bin coinshift_app_cli -- --rpc-url http://127.0.0.1:$USER_RPC <command>"
echo ""
